#!/bin/bash
# 手动部署指南

echo "========================================"
echo "AI日报中心 - 手动部署指南"
echo "========================================"
echo ""
echo "由于服务器限制，请按以下步骤手动完成部署："
echo ""
echo "步骤1: 下载网站文件"
echo "------------------------"
echo "文件位置: /root/.openclaw/workspace/dashboard/"
echo "  - index.html (网站主文件)"
echo "  - reports.json (报告数据)"
echo ""
echo "步骤2: 上传到GitHub"
echo "------------------------"
echo "1. 访问: https://github.com/qingyu3880/ai-reports"
echo "2. 点击 'Add file' → 'Upload files'"
echo "3. 上传以下两个文件:"
echo "   - index.html"
echo "4. 点击 'Commit changes'"
echo ""
echo "步骤3: 配置Vercel自动部署"
echo "------------------------"
echo "1. 访问: https://vercel.com/dashboard"
echo "2. 点击 'Add New Project'"
echo "3. 导入 'qingyu3880/ai-reports' 仓库"
echo "4. 点击 'Deploy'"
echo ""
echo "步骤4: 完成"
echo "------------------------"
echo "Vercel会自动部署，完成后会提供访问地址"
echo ""
echo "========================================"
echo ""

# 显示文件内容摘要
echo "网站文件已准备就绪:"
ls -lh /root/.openclaw/workspace/dashboard/